apiVersion: apps/v1
kind: Deployment
metadata:
  name: srefinal-app
  namespace: srefinal-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: srefinal-app
  template:
    metadata:
      labels:
        app: srefinal-app
    spec:
      containers:
      - name: srefinal-app
        image: registry.k8s.io/pause:3.9 # Этот образ ТОЧНО есть внутри твоего миникуба, скачивать ничего не придётся
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: srefinal-service
  namespace: srefinal-prod
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30085
  selector:
    app: srefinal-app