apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: srefinal-app-monitor
  namespace: monitoring # Кладем в мониторинг к Прометеусу
  labels:
    release: kube-prometheus-stack # Говорим Прометеусу забрать этот монитор
spec:
  selector:
    matchLabels:
      app: srefinal-app # Ищем наш сайт
  namespaceSelector:
    matchNames:
      - srefinal-prod # Ищем в пространстве продакшена
  endpoints:
  - port: web
    path: /metrics
    interval: 15s